DROP TABLE IF EXISTS animal;

CREATE TABLE animal
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    breed VARCHAR,
    age VARCHAR,
    sex VARCHAR,
    info VARCHAR,
    full_text VARCHAR
);

CREATE INDEX ON animal (name);